#!/bin/sh
#
# This is designed to be run on a 1600x900 screen in gnome-terminal with
# Monospace Regular font at size 9 in full screen. No menubars, no
# titlebars.
#
# Built with tmux from source commit: 968296bb

tmux new-session -d -s 'rice_hack'

tmux split-window -h 'bash' # top middle spooky

tmux split-window -h './pipes.sh -d 1 ' # top right pipes

# Those are the three main columns, now split them horizontally

tmux select-pane -t 0
tmux split-window -v 'sleep 5; ./hack.exe www.facebook.com'
tmux split-window -v 'htop'

tmux select-pane -t 3
tmux split-window -v 'cmatrix'

tmux select-pane -t 5
tmux split-window -v 'vis'
tmux split-window -v 'bash'

# At this point all panes are created with the following indexes:
# 0 top left sox noise synthesis
# 1 middle left hack.exe
# 2 bottom left htop
# 3 top middle spooky
# 4 top bottom cmatrix
# 5 top right pipes
# 6 middle right vis
# 7 bottom right cmus

# Resize the hack pane 
tmux select-pane -t 1
tmux resize-pane -D 50
tmux resize-pane -L 12

# Resize the spooky center pane
tmux select-pane -t 3 
tmux resize-pane -R 1

# Respawn the top left pane to play the synth command
tmux respawn-pane -t 0 -k 'play -c 2 -n synth brownnoise'

# Respawn the pane to ensure it has the right dimensions
tmux respawn-pane -t 3 -k 'echo STARTING SPOOKY; sleep 5; lua ./3spooky.lua'

# Toggle the 'full screen' size to trigger cmus to draw correctly, then
# respawn the cmus pane to get it to draw correctly:
tmux resize-pane -Z -t 7 
sleep 3
tmux respawn-pane -t 7 -k 'echo "STARTING CMUS"; sleep 3; cmus'
tmux resize-pane -Z -t 7 

# -2 forces 256 colors 
tmux -2 attach-session -d -t 'rice_hack'
